services:

  keycloak-identity-provider:
    image: dockerhub.repo.x-tention.com/keycloak/keycloak:26.2.5
    container_name: keycloak-identity-provider
    command:
      - start-dev
      - --import-realm
      - --log-level=org.keycloak:DEBUG
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./impex:/opt/keycloak/data/import/
      - ./impex:/tmp/export
